<div class="grid_16">
    <div class="page-header">
        <h2>Login Form <small>|</small> <small>Please logged in first</small></h2>
    </div>
</div>
<div class="span12" style="margin-bottom: 20px;">
    <?php
		echo $this->message;
    ?>
    <br />
    <?php 
        $form = $this->form;
        $form->setAttribute('action', $this->url('user', array('action' => 'login')));
        $form->prepare();
        
        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('email'));
        echo $this->formRow($form->get('password'));
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
    ?>    
</div> 


