			<div class="grid_16">
			  	<div class="page-header">
				    <h2>Página inicial <small>|</small> <small>Gráficos, relatórios e informativos de acesso rápido</small></h2>
				</div>
			</div>

            <div class="grid_16">
                <div class="alert alert-block">
                    <button data-dismiss="alert" class="close" type="button">×</button>
                    <h4>Atenção! a</h4>
                    Verifique as Ordens de Serviço em aberto.
                </div>
            </div>

            <div class="box grid_8" style="opacity: 1;">
                <h2 class="box_head grad_black">Gráfico de OS</h2>
                <div class="controls">
                    <a class="grabber" href="#"></a>
                    <a class="toggle" href="#"></a>
                </div>
                <div class="toggle_container">
                    <div class="block" style="opacity: 1;">
                        <div class="section">
                            <p>Content goes here</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box grid_8" style="opacity: 1;">
                <h2 class="box_head grad_black">Relatório</h2>
                <div class="controls">
                    <a class="grabber" href="#"></a>
                    <a class="toggle" href="#"></a>
                </div>
                <div class="toggle_container">
                    <div class="block" style="opacity: 1;">
                        <div class="section">
                            <p>Content goes here</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box grid_8" style="opacity: 1;">
                <h2 class="box_head grad_black">Estatística</h2>
                <div class="controls">
                    <a class="grabber" href="#"></a>
                    <a class="toggle" href="#"></a>
                </div>
                <div class="toggle_container">
                    <div class="block" style="opacity: 1;">
                        <div class="section">
                            <p>Content goes here</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box grid_8" style="opacity: 1;">
                <h2 class="box_head grad_black">Variações</h2>
                <div class="controls">
                    <a class="grabber" href="#"></a>
                    <a class="toggle" href="#"></a>
                </div>
                <div class="toggle_container">
                    <div class="block" style="opacity: 1;">
                        <div class="section">
                            <p>Content goes here</p>
                        </div>
                    </div>
                </div>
            </div>
